
all:
	$(CXX) $(CXXFLAGS) $(CFLAGS) $(LDFLAGS) -o hyperkin-loading hyperkin-loading.cpp -lEGL -lGLESv2 -lSDL2 -lSDL2_image -lSDL2_ttf -lpthread -lSDL2_mixer -lasound
	$(CXX) $(CXXFLAGS) $(CFLAGS) $(LDFLAGS) -o hyperkin-crc hyperkin-crc.cpp
